name: Close Issues on Comment

on:
  issue_comment:
    types: [created]

jobs:
  close_issue_on_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue if comment contains 'close'
        uses: actions/github-script@v6
        with:
          script: |
            const comment = context.payload.comment.body.toLowerCase();
            const issueNumber = context.payload.issue.number;

            // Check if the comment includes the word "close"
            if (comment.includes('close')) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                state: 'closed'
              });
              console.log(`Closed issue #${issueNumber} based on comment: ${comment}`);
            } else {
              console.log(`Comment does not contain 'close'; action skipped.`);
            }
